services:
  backend:
    build: .
    env_file:
      - .env
    container_name: union_ganadera_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - localstack
    networks:
      - union_net

  db:
    image: postgres:15
    container_name: union_ganadera_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - union_net

  localstack:
    image: localstack/localstack
    container_name: union_ganadera_s3
    ports:
      - "4566:4566"
    env_file:
      - .env
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - union_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: union_ganadera_pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - union_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  localstack_data:
  pgadmin_data:


networks:
  union_net:
    driver: bridge
